version: "3.8"

services:
  discord-bot:
    build: .
    container_name: fin3st-discord-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      GUILD_ID: ${GUILD_ID}
      NODE_ENV: production
      PORT: 8080
      STATUS_TOKEN: ${STATUS_TOKEN}   # optional für Schutz /status
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/healthz || wget -qO- http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s