version: "3.8"

services:
  discord-bot:
    build: .
    container_name: fin3st-discord-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      GUILD_ID: ${GUILD_ID}
      NODE_ENV: production
